import base64

frames = [
    "kKZggpZAdpCmYJZAQGED8AAAPgABAAEAKQAAAAA/AAFvEgM6bxIDOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPQo/PzMzsz1I4QI/FK43PyncAkEAAD8AAXYAAAA3QQAAOEEAADZBAAA1QUjhAkEMAms+ZuYCQQ4tcr7ueAAAQQABQkNO",
    "kKZggpZAdpCmYJZAQGED8AAAPgABAAEAKQAAAAA/AAFvEgM6AAAAAG8SAzoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7FH4P1K4jj4Urk8/Uri2PwrXAkEAAD8AAXYAAAA1QQAAN0EAADVBAAA0QSncAkEMAms+SOECQSGwcr7ueAAAQQABQkNO",
    "kKZggpZAdpCmYJZAQGED8AAAPgABAAEAKQAAAAA/AAEAAAAAbxIDOm8SAzoAAAAAAAAAAAAAAABvEgM6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPQoVQD0KVz4pXNc/7FHcPwrXAkEAAD8AAXYAAAA0QQAANkEAADRBAAA0QSncAkEfhWs+SOECQTMzc77ueAAAQQABQkNO",
    "kKZggpZAdpCmYJZAQGED8AAAPgABAAEAKQAAAAA/AAEAAAAAAAAAAAAAAAAj2/k+4XqUPQAAAADD9Yg+AAAAAAAAAAAAAAAAmpkJQAAAoD4AAAAAAAAMQAAAAAAAAAAA7FFoPylcjEAAAItACtd/QApXA0EAAD8AAXYAAAAzQQAANUEAADNBAAAzQXE9A0FQjRe9UjgDQSlcDz3ueAAAQQABQkNO"
]


for i, s in enumerate(frames, 1):
    b = base64.b64decode(s)
    hex_str = " ".join(f"{x:02x}" for x in b)
    print(hex_str)
    print()